# Generated by Django 5.0.4 on 2024-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='drones.jpg', upload_to='profile_images/'),
        ),
    ]
