# Generated by Django 5.0.4 on 2024-05-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_api', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', upload_to='profile_images/'),
        ),
    ]
