# Generated by Django 5.0.4 on 2024-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_api', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
