# Generated by Django 5.0.4 on 2024-08-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_api', '0005_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
