# Generated by Django 5.0.10 on 2025-06-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fond_api', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['title'], 'verbose_name_plural': 'Items'},
        ),
    ]
