# Generated by Django 5.0.10 on 2025-09-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fond_api", "0007_alter_item_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
    ]
